framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
        routing:
            # Route this message class to the async transport
            App\Message\TransferFundsMessage: async
